# Generated by Django 3.1.5 on 2021-02-21 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crew_name', models.CharField(blank=True, max_length=100, null=True)),
                ('tag_line', models.CharField(blank=True, max_length=100, null=True)),
                ('netnet', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('about', models.CharField(blank=True, max_length=1000, null=True)),
                ('netnet', models.CharField(blank=True, max_length=1000, null=True)),
                ('avatar_img', models.FileField(blank=True, null=True, upload_to='pics/')),
                ('affiliation', models.CharField(blank=True, max_length=1000, null=True)),
                ('crew_name', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='fest.crew')),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
